// Rajrani Hospital & Relax Diagnostics - Complete Data
// Contact बदलने के लिए यहां edit करें

export const hospitalInfo = {
  name: "Rajrani Hospital",
  nameHindi: "राजरानी हॉस्पिटल",
  tagline: "Quality Healthcare for All",
  taglineHindi: "सबके लिए गुणवत्तापूर्ण स्वास्थ्य सेवा",
  established: "2005",
  accreditation: "ISO Certified | NABH Standards",
  accreditationHindi: "आईएसओ प्रमाणित | एनएबीएच मानक",
  phone: "+91-8700628028",
  whatsapp: "918700628028",
  emergency: "+91-8700628028",
  email: "abhinay.gautam0072@gmail.com",
  address: "Plot No. D-3, Main Market, Old Kondli, New Delhi, Delhi 110096",
  addressHindi: "प्लॉट नं. D-3, मेन मार्केट, पुरानी कोंडली, नई दिल्ली 110096",
  googleMapsLink: "https://maps.app.goo.gl/P5xfA87tjCE6Bit79",
  googleMapsEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3502.5!2d77.323!3d28.608!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cfb0a8c6b3d9d%3A0x123456789!2sRAJRANI%20HOSPITAL%2C%20Old%20Kondli!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin",
  workingHours: "Open 24 Hours",
  workingHoursHindi: "24 घंटे खुला",
  yearsExperience: "36+",
  managingDirector: "Dr. Sandeep Kumar",
  managingDirectorHindi: "डॉ. संदीप कुमार",
  patientsServed: "50,000+",
  facebook: "https://facebook.com/rajranihospital",
  instagram: "https://instagram.com/rajranihospital"
};

// Relax Diagnostics Center
export const diagnosticsInfo = {
  name: "Relax Diagnostics",
  nameHindi: "रिलैक्स डायग्नोस्टिक्स",
  tagline: "NABL Accredited Diagnostic Center",
  taglineHindi: "एनएबीएल मान्यता प्राप्त डायग्नोस्टिक सेंटर",
  phone: "+91-9990187799",
  alternatePhone: "+91-9560031087",
  email: "relaxdiagnostics@gmail.com",
  address: "D-1, Main Market, Near SBI, Kondli Extension, Kondli, New Delhi, Delhi 110096",
  addressHindi: "D-1, मेन मार्केट, SBI के पास, कोंडली एक्सटेंशन, नई दिल्ली 110096",
  googleMapsLink: "https://maps.app.goo.gl/qbTabEgYtzquN3TC7",
  workingHours: "8 AM -10 PM (Mon-Sat)",
  workingHoursHindi: "सुबह 8 - शाम 10 (सोम-शनि)",
  rating: "4.5",
  accreditation: "NABL Accredited | CGHS Empanelled",
  accreditationHindi: "एनएबीएल मान्यता प्राप्त | सीजीएचएस पैनल",
  managedBy: "Dr. Sandeep Kumar",
  featureHighlights: [
    {
      title: "Digital X-Ray",
      titleHindi: "Digital X-Ray",
      subtitle: "On 500mA machine",
      subtitleHindi: "500mA machine par",
      icon: "Scan"
    },
    {
      title: "2D Echo Available",
      titleHindi: "2D Echo Available",
      subtitle: "Cardiac imaging support",
      subtitleHindi: "Cardiac imaging support",
      icon: "HeartPulse"
    },
    {
      title: "Colour Ultrasound",
      titleHindi: "Colour Ultrasound",
      subtitle: "Fast diagnostic access",
      subtitleHindi: "Fast diagnostic access",
      icon: "Monitor"
    }
  ],
  services: [
    { name: "Complete Blood Count (CBC)", nameHindi: "पूर्ण रक्त गणना", price: "₹150-550" },
    { name: "Liver Function Test (LFT)", nameHindi: "लिवर फंक्शन टेस्ट", price: "₹350-800" },
    { name: "Kidney Function Test (KFT)", nameHindi: "किडनी फंक्शन टेस्ट", price: "₹400-900" },
    { name: "Lipid Profile", nameHindi: "लिपिड प्रोफाइल", price: "₹400-700" },
    { name: "Thyroid Profile (T3, T4, TSH)", nameHindi: "थायरॉयड प्रोफाइल", price: "₹500-900" },
    { name: "Blood Sugar (Fasting/PP)", nameHindi: "ब्लड शुगर", price: "₹50-150" },
    { name: "HbA1c (Diabetes)", nameHindi: "एचबीए1सी", price: "₹400-600" },
    { name: "Urine Routine", nameHindi: "यूरिन टेस्ट", price: "₹100-200" },
    { name: "Ultrasound (Abdomen)", nameHindi: "अल्ट्रासाउंड (पेट)", price: "₹500-1000" },
    { name: "Ultrasound (Pregnancy)", nameHindi: "अल्ट्रासाउंड (प्रेगनेंसी)", price: "₹600-1200" },
    { name: "X-Ray", nameHindi: "एक्स-रे", price: "₹200-500" },
    { name: "ECG", nameHindi: "ईसीजी", price: "₹150-300" },
    { name: "Vitamin D Test", nameHindi: "विटामिन डी टेस्ट", price: "₹600-1000" },
    { name: "Vitamin B12 Test", nameHindi: "विटामिन बी12 टेस्ट", price: "₹500-800" },
    { name: "Complete Health Checkup", nameHindi: "पूर्ण स्वास्थ्य जांच", price: "₹1500-3000" }
  ],
  offerCategories: [
    {
      key: "routine",
      title: "Routine and preventive tests",
      titleHindi: "Routine and preventive tests",
      description: "CBC se thyroid aur sugar tak daily lab essentials.",
      tests: [
        { name: "CBC", nameHindi: "CBC", originalPrice: 400, offerPrice: 200 },
        { name: "CBC & ESR", nameHindi: "CBC & ESR", originalPrice: 450, offerPrice: 300 },
        { name: "LFT", nameHindi: "LFT", originalPrice: 600, offerPrice: 400 },
        { name: "KFT", nameHindi: "KFT", originalPrice: 600, offerPrice: 400 },
        { name: "Lipid Profile", nameHindi: "Lipid Profile", originalPrice: 800, offerPrice: 400 },
        { name: "TSH", nameHindi: "TSH", originalPrice: 400, offerPrice: 200 },
        { name: "TFT", nameHindi: "TFT", originalPrice: 800, offerPrice: 500 },
        { name: "Vit-D", nameHindi: "Vit-D", originalPrice: 1500, offerPrice: 1000 },
        { name: "Vit B12", nameHindi: "Vit B12", originalPrice: 1200, offerPrice: 1000 },
        { name: "Free TFT", nameHindi: "Free TFT", originalPrice: 700, offerPrice: 500 },
        { name: "HBA1C", nameHindi: "HBA1C", originalPrice: 600, offerPrice: 400 },
        { name: "BSF", nameHindi: "BSF", originalPrice: 100, offerPrice: 50 },
        { name: "BSPP", nameHindi: "BSPP", originalPrice: 100, offerPrice: 50 },
        { name: "Blood Group", nameHindi: "Blood Group", originalPrice: 200, offerPrice: 100 }
      ]
    },
    {
      key: "inflammation",
      title: "Markers and speciality support",
      titleHindi: "Markers and speciality support",
      description: "Inflammation, vitamin and follow-up markers at reduced rates.",
      tests: [
        { name: "CRP", nameHindi: "CRP", originalPrice: 500, offerPrice: 400 },
        { name: "ASO Titer", nameHindi: "ASO Titer", originalPrice: 500, offerPrice: 300 },
        { name: "RA Factor", nameHindi: "RA Factor", originalPrice: 400, offerPrice: 300 },
        { name: "VDRL", nameHindi: "VDRL", originalPrice: 500, offerPrice: 300 },
        { name: "Viral Marker", nameHindi: "Viral Marker", originalPrice: 1700, offerPrice: 1000 },
        { name: "Serum IgE", nameHindi: "Serum IgE", originalPrice: 600, offerPrice: 450 },
        { name: "Anti TPO", nameHindi: "Anti TPO", originalPrice: 1200, offerPrice: 1000 }
      ]
    },
    {
      key: "infection",
      title: "Fever and infection panels",
      titleHindi: "Fever and infection panels",
      description: "Dengue, typhoid, malaria aur viral screening offers.",
      tests: [
        { name: "Malaria Ag", nameHindi: "Malaria Ag", originalPrice: 600, offerPrice: 400 },
        { name: "Dengue Antigen", nameHindi: "Dengue Antigen", originalPrice: 800, offerPrice: 600 },
        { name: "Dengue IgG / IgM", nameHindi: "Dengue IgG / IgM", originalPrice: 1200, offerPrice: 700 },
        { name: "Typhoid", nameHindi: "Typhoid", originalPrice: 600, offerPrice: 400 },
        { name: "Widal", nameHindi: "Widal", originalPrice: 300, offerPrice: 200 },
        { name: "Hep-A", nameHindi: "Hep-A", originalPrice: 1000, offerPrice: 900 },
        { name: "Hep-B", nameHindi: "Hep-B", originalPrice: 500, offerPrice: 400 },
        { name: "Hep-C", nameHindi: "Hep-C", originalPrice: 900, offerPrice: 600 },
        { name: "Hep-E", nameHindi: "Hep-E", originalPrice: 1300, offerPrice: 1000 },
        { name: "HIV", nameHindi: "HIV", originalPrice: 500, offerPrice: 400 }
      ]
    },
    {
      key: "hormone",
      title: "Hormone and women care tests",
      titleHindi: "Hormone and women care tests",
      description: "Reproductive, thyroid aur ANC related focused profiles.",
      tests: [
        { name: "LH, FSH, Prolactin, TSH", nameHindi: "LH, FSH, Prolactin, TSH", originalPrice: 1500, offerPrice: 1000 },
        { name: "PHCG", nameHindi: "PHCG", originalPrice: 700, offerPrice: 500 },
        { name: "Torch Profile", nameHindi: "Torch Profile", originalPrice: 2200, offerPrice: 1300 },
        { name: "ANC Profile", nameHindi: "ANC Profile", originalPrice: 2000, offerPrice: 1400 }
      ]
    },
    {
      key: "procedures",
      title: "Procedure and speciality tests",
      titleHindi: "Procedure and speciality tests",
      description: "Sample-based speciality tests and supportive lab procedures.",
      tests: [
        { name: "Semen Analysis", nameHindi: "Semen Analysis", originalPrice: 500, offerPrice: 200 },
        { name: "S. Amylase", nameHindi: "S. Amylase", originalPrice: 800, offerPrice: 400 },
        { name: "S. Lipase", nameHindi: "S. Lipase", originalPrice: 600, offerPrice: 400 },
        { name: "FNAC", nameHindi: "FNAC", originalPrice: 1500, offerPrice: 1000 }
      ]
    }
  ],
  comboOffer: {
    title: "Quick screening combo",
    titleHindi: "Quick screening combo",
    tests: ["CBC", "Blood Group", "Random Sugar", "Viral Marker", "Urine R/M", "TSH"],
    note: "Ask at reception for the current bundled rate."
  },
  packageCollections: [
    {
      key: "preventive",
      title: "Full body and preventive packages",
      titleHindi: "Full body and preventive packages",
      description: "Daily preventive panels and annual check-up bundles.",
      packages: [
        {
          code: "R-001",
          title: "Full Body Check-Up",
          titleHindi: "Full Body Check-Up",
          parameterCount: 70,
          price: "Rs. 1800",
          testsIncluded: ["Vitamin B12", "CBC", "ESR", "LFT", "KFT", "Lipid Profile", "TFT", "BSF", "HbA1c", "Urine R/M"]
        },
        {
          code: "R-002",
          title: "Full Body Check-Up",
          titleHindi: "Full Body Check-Up",
          parameterCount: 54,
          price: "Rs. 1400",
          testsIncluded: ["Vitamin D", "CBC", "ESR", "HbA1c", "LFT", "TFT", "Urine R/M"]
        },
        {
          code: "R-003",
          title: "Full Body Check-Up",
          titleHindi: "Full Body Check-Up",
          parameterCount: 71,
          price: "Rs. 1700",
          testsIncluded: ["Vitamin D", "CBC", "ESR", "HbA1c", "LFT", "KFT with electrolytes", "Lipid Profile", "Thyroid Profile", "BSF", "Urine R/M"]
        },
        {
          code: "R-004",
          title: "Full Body Check-Up",
          titleHindi: "Full Body Check-Up",
          parameterCount: 58,
          price: "Rs. 1700",
          testsIncluded: ["CBC", "ESR", "LFT", "KFT with electrolytes", "BSF", "Vitamin D3", "Vitamin B12", "Urine R/M"]
        },
        {
          code: "R-005",
          title: "Full Body Check-Up",
          titleHindi: "Full Body Check-Up",
          parameterCount: 75,
          price: "Rs. 2200",
          testsIncluded: ["CBC", "ESR", "HbA1C", "LFT", "KFT with electrolytes", "Lipid Profile", "TFT", "Thyroid Profile", "Vitamin B12", "BSF"]
        },
        {
          code: "R-006",
          title: "General Check-Up Panel",
          titleHindi: "General Check-Up Panel",
          parameterCount: 6,
          price: "Call for offer",
          priceNote: "Poster price was not fully visible.",
          testsIncluded: ["CBC", "BSF", "Bilirubin T/D", "TSH", "Urine R/M", "Serum Creatinine Test"]
        },
        {
          code: "R-007",
          title: "Full Body Check-Up",
          titleHindi: "Full Body Check-Up",
          parameterCount: 66,
          price: "Rs. 2000",
          testsIncluded: ["CBC", "ESR", "eGFR", "LFT", "KFT", "Lipid Profile", "Basic Vitamin D3", "Vitamin B12", "Urine R/M"]
        }
      ]
    },
    {
      key: "fever",
      title: "Fever and thyroid offer packages",
      titleHindi: "Fever and thyroid offer packages",
      description: "Seasonal fever workups and focused thyroid package options.",
      packages: [
        {
          code: "R-008",
          title: "Fever Profile",
          titleHindi: "Fever Profile",
          parameterCount: 32,
          price: "Rs. 800",
          testsIncluded: ["CBC", "LFT", "Typhoid IgG", "Typhoid IgM"]
        },
        {
          code: "R-009",
          title: "Fever Profile",
          titleHindi: "Fever Profile",
          parameterCount: 18,
          price: "Rs. 900",
          testsIncluded: ["CBC", "ESR", "Malaria (Ag)", "Widal Test", "Urine R/M"]
        },
        {
          code: "R-010",
          title: "Fever Profile",
          titleHindi: "Fever Profile",
          parameterCount: 7,
          price: "Rs. 1000",
          testsIncluded: ["Malaria Ag", "Dengue IgG", "Dengue IgM", "Elisa NS1", "Typhoid IgG", "Typhoid IgM"]
        },
        {
          code: "R-011",
          title: "Fever Profile",
          titleHindi: "Fever Profile",
          parameterCount: 41,
          price: "Rs. 1900",
          testsIncluded: ["CBC", "ESR", "LFT", "KFT", "Malaria Ag", "Dengue (IgG, IgM, NS1)", "Typhoid IgG / IgM", "Widal", "Urine R/M", "CRP"]
        },
        {
          code: "R-012",
          title: "Thyroid Profile",
          titleHindi: "Thyroid Profile",
          parameterCount: 3,
          price: "Call for offer",
          priceNote: "Poster price was covered by glare.",
          testsIncluded: ["T3", "T4", "TSH"]
        }
      ]
    },
    {
      key: "speciality",
      title: "Speciality and monitoring profiles",
      titleHindi: "Speciality and monitoring profiles",
      description: "Anemia, arthritis, cardiac, fertility and screening packages.",
      packages: [
        {
          code: "R1001",
          title: "Anemia Profile (Nutritional)",
          titleHindi: "Anemia Profile (Nutritional)",
          parameterCount: 26,
          price: "CRI MRP Rs. 2500",
          testsIncluded: ["CBC", "Peripheral smear examination", "Ferritin", "Iron", "Total iron binding capacity", "Transferin saturation", "Vitamin B12", "Folic Acid"]
        },
        {
          code: "R1002",
          title: "Arthritis Profile Basic",
          titleHindi: "Arthritis Profile Basic",
          parameterCount: 25,
          price: "CRI MRP Rs. 2000",
          testsIncluded: ["CBC", "ESR", "CRP Quantitative", "Uric Acid", "Calcium", "RA Factor Quantitative", "ASO Titer Quantitative"]
        },
        {
          code: "R1003",
          title: "Bad Obstetric History (BOH) Profile",
          titleHindi: "Bad Obstetric History (BOH) Profile",
          parameterCount: 11,
          price: "CRI MRP Rs. 5400",
          testsIncluded: ["TSH", "Lupus anticoagulant", "ANA", "Anti phospholipid antibody IgG", "Anti phospholipid antibody IgM", "CMV IgM", "CMV IgG", "HSV 1 & 2 IgG", "Rubella IgM", "Toxoplasma Gondii IgG", "Toxoplasma Gondii IgM"]
        },
        {
          code: "R1004",
          title: "Basic Arthritis Panel",
          titleHindi: "Basic Arthritis Panel",
          parameterCount: 24,
          price: "CRI MRP Rs. 2450",
          testsIncluded: ["Calcium", "CRP Quantitative", "Serum Uric Acid", "ESR", "CBC", "RA Factor Quantitative"]
        },
        {
          code: "R1005",
          title: "Cancer Screening Male",
          titleHindi: "Cancer Screening Male",
          parameterCount: 22,
          price: "CRI MRP Rs. 4500",
          testsIncluded: ["CBC", "Alpha Feto Protein (AFP)", "Carcino Embryonic Antigen (CEA)", "Prostate Specific Antigen (PSA) Total"]
        },
        {
          code: "R1006",
          title: "Cardiac Monitoring Profile",
          titleHindi: "Cardiac Monitoring Profile",
          parameterCount: 4,
          price: "CRI MRP Rs. 4500",
          testsIncluded: ["Creatinine Kinase (CPK)", "Creatinine Kinase MB (CK-MB)", "LDH", "Pro-Beta Natriuretic Peptide (BNP)"]
        },
        {
          code: "R1007",
          title: "Cardiac Monitoring Profile-1",
          titleHindi: "Cardiac Monitoring Profile-1",
          parameterCount: 4,
          price: "CRI MRP Rs. 2000",
          testsIncluded: ["Creatinine Kinase (CPK)", "Creatinine Kinase (CPK MB)", "LDH Serum", "Homocysteine"]
        },
        {
          code: "R1008",
          title: "Diabetes Monitoring Profile",
          titleHindi: "Diabetes Monitoring Profile",
          parameterCount: 6,
          price: "CRI MRP Rs. 1200",
          testsIncluded: ["SPOT Microalbumin", "Microalbumin / Creatinine Ratio", "Glucose (Fasting)", "Glycosylated Hemoglobin (HbA1c) by IFCC", "Estimated Average Glucose"]
        },
        {
          code: "R1009",
          title: "Fertility Profile Female",
          titleHindi: "Fertility Profile Female",
          parameterCount: 5,
          price: "CRI MRP Rs. 1200",
          testsIncluded: ["FSH", "LH", "Prolactin", "TSH", "Estradiol"]
        },
        {
          code: "R1010",
          title: "Fertility Profile Male",
          titleHindi: "Fertility Profile Male",
          parameterCount: 5,
          price: "CRI MRP Rs. 1200",
          testsIncluded: ["FSH", "LH", "Prolactine", "Testosterone Total"]
        },
        {
          code: "R1011",
          title: "Triple Marker Maternal Screen",
          titleHindi: "Triple Marker Maternal Screen",
          parameterCount: 4,
          price: "CRI MRP Rs. 1800",
          testsIncluded: ["Serum Beta HCG", "Unconjugated alpha feto protein", "Estriol", "Maternal screening marker calculation"]
        }
      ]
    }
  ]
};

export const services = [
  {
    id: 1,
    title: "OPD Services",
    titleHindi: "ओपीडी सेवाएं",
    description: "Comprehensive outpatient department with specialist consultations",
    descriptionHindi: "विशेषज्ञ परामर्श के साथ व्यापक बाह्य रोगी विभाग",
    icon: "Stethoscope",
    featured: true,
    image: "/images/about/trust-01.jpg",
    details: ["General Medicine", "Specialist Consultations", "Health Check-ups", "Follow-up Care", "Prescription Services"],
    consultationFee: 500,
    availability: "11AM - 2PM   &   7PM - 10PM",
    type: "consultation"
  },
  {
    id: 2,
    title: "Emergency Care",
    titleHindi: "आपातकालीन सेवा",
    description: "24/7 emergency services with immediate medical attention",
    descriptionHindi: "तत्काल चिकित्सा सहायता के साथ 24/7 आपातकालीन सेवाएं",
    icon: "Ambulance",
    featured: true,
    image: "/images/services/service-emergency.jpg",
    details: ["24/7 Emergency", "Trauma Care", "Critical Care", "Ambulance Service", "First Aid"],
    consultationFee: 1000,
    availability: "24x7",
    type: "emergency"
  },
  {
    id: 3,
    title: "Physiotherapy",
    titleHindi: "फिजियोथेरेपी",
    description: "Expert physiotherapy for pain relief and rehabilitation",
    descriptionHindi: "दर्द निवारण और पुनर्वास के लिए विशेषज्ञ फिजियोथेरेपी",
    icon: "HeartPulse",
    featured: false,
    image: "/images/about/story-01.jpg",
    details: ["Pain Management", "Post-Surgery Rehab", "Sports Injury", "Back Pain", "Joint Mobilization"],
    consultationFee: 400,
    availability: "10 AM - 6 PM",
    type: "consultation"
  },
  {
    id: 4,
    title: "Diagnostic Lab",
    titleHindi: "डायग्नोस्टिक लैब",
    description: "Complete diagnostic laboratory with same-day results",
    descriptionHindi: "उसी दिन रिपोर्ट के साथ पूर्ण डायग्नोस्टिक लैब",
    icon: "TestTube",
    featured: true,
    image: "/images/about/story-02.jpg",
    details: ["Blood Tests", "Pathology", "ECG", "Same-day Results", "Home Collection"],
    consultationFee: 0,
    availability: "8 AM - 8 PM",
    type: "test"
  },
  {
    id: 5,
    title: "X-Ray & Radiology",
    titleHindi: "एक्स-रे और रेडियोलॉजी",
    description: "Digital X-Ray and advanced radiology services",
    descriptionHindi: "डिजिटल एक्स-रे और उन्नत रेडियोलॉजी सेवाएं",
    icon: "Scan",
    featured: true,
    image: "/images/services/service-xray.jpg",
    details: ["Digital X-Ray", "Chest X-Ray", "Bone X-Ray", "Quick Reports", "Expert Analysis"],
    consultationFee: 300,
    availability: "9 AM - 6 PM",
    type: "test"
  },
  {
    id: 6,
    title: "Ultrasound",
    titleHindi: "अल्ट्रासाउंड",
    description: "Advanced ultrasound imaging for accurate diagnosis",
    descriptionHindi: "सटीक निदान के लिए उन्नत अल्ट्रासाउंड इमेजिंग",
    icon: "Monitor",
    featured: true,
    image: "/images/about/story-03.jpg",
    details: ["Abdominal Ultrasound", "Pregnancy Scan", "Cardiac Echo", "Thyroid Scan", "Pelvic Scan"],
    consultationFee: 500,
    availability: "9 AM - 6 PM",
    type: "test"
  },
  {
    id: 7,
    title: "General Surgery",
    titleHindi: "जनरल सर्जरी",
    description: "Expert surgical care with modern operation theaters",
    descriptionHindi: "आधुनिक ऑपरेशन थियेटर के साथ विशेषज्ञ सर्जिकल देखभाल",
    icon: "Scissors",
    featured: false,
    image: "/images/services/service-surgery.jpg",
    details: ["Laparoscopic Surgery", "Minor Surgery", "Major Surgery", "Post-op Care", "Day Care Surgery"],
    consultationFee: 800,
    availability: "10 AM - 6 PM",
    type: "consultation"
  },
  {
    id: 8,
    title: "Orthopedics",
    titleHindi: "ऑर्थोपेडिक्स",
    description: "Bone and joint care with physiotherapy",
    descriptionHindi: "फिजियोथेरेपी के साथ हड्डी और जोड़ों की देखभाल",
    icon: "Bone",
    featured: false,
    image: "/images/services/service-ortho.jpg",
    details: ["Fracture Care", "Joint Replacement", "Sports Injury", "Physiotherapy", "Spine Care"],
    consultationFee: 700,
    availability: "11 AM - 6 PM",
    type: "consultation"
  },
  {
    id: 9,
    title: "Gynecology",
    titleHindi: "स्त्री रोग",
    description: "Complete women's healthcare and maternity care",
    descriptionHindi: "महिलाओं की पूर्ण स्वास्थ्य देखभाल और मातृत्व देखभाल",
    icon: "Heart",
    featured: false,
    image: "/images/about/value-01.jpg",
    details: ["Pregnancy Care", "Normal Delivery", "C-Section", "Women's Health", "Infertility"],
    consultationFee: 1000,
    availability: "10 AM - 5 PM",
    type: "consultation"
  },
  {
    id: 10,
    title: "Pediatrics",
    titleHindi: "बाल रोग",
    description: "Specialized care for children with vaccination",
    descriptionHindi: "टीकाकरण के साथ बच्चों की विशेष देखभाल",
    icon: "Baby",
    featured: false,
    image: "/images/about/trust-02.jpg",
    details: ["Child Health", "Vaccination", "Newborn Care", "Growth Monitoring", "Pediatric Emergency"],
    consultationFee: 500,
    availability: "9 AM - 2 PM",
    type: "consultation"
  }
];


export const consultantDoctors = [
  {
    id: 1,
    name: "Dr. Raj Rani",
    nameHindi: "Dr. Raj Rani",
    specialization: "Obstetrician & Gynaecologist",
    specializationHindi: "Obstetrician & Gynaecologist",
    experience: "Daily OPD",
    education: "MBBS, PG, DMCH (Director)",
    image: "/images/doctors/doctor-03.jpg",
    availability: "Daily",
    timings: ["11 AM - 2 Noon", "7 PM - 9 PM"],
    consultationFee: 300,
    feeLabel: "Rs.300",
    languages: ["Hindi", "English"],
    specialties: ["Pregnancy Care", "Women's Health", "Gynecology"],
    about: "Director and senior obstetrician-gynaecologist available daily.",
    isAvailable: true,
    onCall: false
  },
  {
    id: 2,
    name: "Dr. Rakhi Rawat",
    nameHindi: "Dr. Rakhi Rawat",
    specialization: "Obstetrician & Gynaecologist",
    specializationHindi: "Obstetrician & Gynaecologist",
    experience: "Scheduled Visit",
    education: "MBBS, MS",
    image: "/images/doctors/doctor-02.jpg",
    availability: "As Scheduled",
    timings: ["12 PM - 1 PM"],
    consultationFee: 400,
    feeLabel: "Rs.400",
    languages: ["Hindi", "English"],
    specialties: ["Gynecology Consultation", "Women's Health", "Clinic Follow-up"],
    about: "Scheduled gynecology consultation support.",
    isAvailable: true,
    onCall: false
  },
  {
    id: 3,
    name: "Dr. Asha Patra",
    nameHindi: "Dr. Asha Patra",
    specialization: "Obstetrician & Gynaecologist",
    specializationHindi: "Obstetrician & Gynaecologist",
    experience: "On Call",
    education: "MBBS, DGO",
    image: "/images/doctors/doctor-01.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: 400,
    feeLabel: "Rs.400",
    languages: ["Hindi", "English"],
    specialties: ["Gynecology Consultation", "Emergency Women's Care", "Pregnancy Advice"],
    about: "Available on call for gynecology support.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 4,
    name: "Dr. Sandeep Kumar",
    nameHindi: "Dr. Sandeep Kumar",
    specialization: "Internal Medicine",
    specializationHindi: "Internal Medicine",
    experience: "Daily OPD",
    education: "MBBS, MD",
    image: "/images/doctors/doctor-04.jpg",
    availability: "Daily",
    timings: ["10 AM - 2 PM", "6 PM - 9 PM"],
    consultationFee: 300,
    feeLabel: "Rs.300",
    languages: ["Hindi", "English"],
    specialties: ["General Medicine", "BP / Diabetes", "Fever & Infection"],
    about: "Internal medicine consultant available in morning and evening OPD.",
    isAvailable: true,
    onCall: false
  },
  {
    id: 5,
    name: "Dr. Rakesh Singh",
    nameHindi: "Dr. Rakesh Singh",
    specialization: "Internal Medicine",
    specializationHindi: "Internal Medicine",
    experience: "Evening OPD",
    education: "MBBS, DMCH (Ex. CMO LBSH)",
    image: "/images/doctors/doctor-05.jpg",
    availability: "Daily",
    timings: ["7 PM - 9 PM"],
    consultationFee: 300,
    feeLabel: "Rs.300",
    languages: ["Hindi", "English"],
    specialties: ["Internal Medicine", "Chronic Care", "Evening Consultation"],
    about: "Evening internal medicine consultation by former CMO, LBSH.",
    isAvailable: true,
    onCall: false
  },
  {
    id: 6,
    name: "Dr. B. P. Gupta",
    nameHindi: "Dr. B. P. Gupta",
    specialization: "General Surgeon",
    specializationHindi: "General Surgeon",
    experience: "Surgical OPD",
    education: "MBBS, MS",
    image: "/images/doctors/doctor-06.jpg",
    availability: "As Scheduled",
    timings: ["8 PM - 9 PM"],
    consultationFee: 500,
    feeLabel: "Rs.500",
    languages: ["Hindi", "English"],
    specialties: ["General Surgery", "Minor Procedures", "Surgical Review"],
    about: "General surgery consultation in evening OPD.",
    isAvailable: true,
    onCall: false
  },
  {
    id: 7,
    name: "Dr. V. K. Gupta",
    nameHindi: "Dr. V. K. Gupta",
    specialization: "General Surgeon",
    specializationHindi: "General Surgeon",
    experience: "On Call",
    education: "MBBS, MS",
    image: "/images/doctors/doctor-01.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: 500,
    feeLabel: "Rs.500",
    languages: ["Hindi", "English"],
    specialties: ["General Surgery", "Surgical Consultation", "Emergency Surgical Advice"],
    about: "On-call surgery consultation support.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 8,
    name: "Dr. Waseem Farooqui",
    nameHindi: "Dr. Waseem Farooqui",
    specialization: "Cardiologist",
    specializationHindi: "Cardiologist",
    experience: "On Call",
    education: "MBBS, DM",
    image: "/images/doctors/doctor-02.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: 1000,
    feeLabel: "Rs.1000",
    languages: ["Hindi", "English"],
    specialties: ["Cardiology", "Heart Consultation", "ECG Review"],
    about: "On-call cardiology specialist consultation.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 9,
    name: "Dr. Jitendra Kumar",
    nameHindi: "Dr. Jitendra Kumar",
    specialization: "Orthopaedic",
    specializationHindi: "Orthopaedic",
    experience: "Mon-Sat OPD",
    education: "MBBS, MS (Ortho.)",
    image: "/images/doctors/doctor-03.jpg",
    availability: "Monday - Saturday",
    timings: ["8 PM - 9 PM"],
    consultationFee: 500,
    feeLabel: "Rs.500",
    languages: ["Hindi", "English"],
    specialties: ["Bone & Joint Care", "Fracture Care", "Orthopaedic Review"],
    about: "Orthopaedic consultation from Monday to Saturday.",
    isAvailable: true,
    onCall: false
  },
  {
    id: 10,
    name: "Dr. Arvind Tiwari",
    nameHindi: "Dr. Arvind Tiwari",
    specialization: "Urologist",
    specializationHindi: "Urologist",
    experience: "On Call",
    education: "MBBS, MCh",
    image: "/images/doctors/doctor-04.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: 1000,
    feeLabel: "Rs.1000",
    languages: ["Hindi", "English"],
    specialties: ["Urology", "Kidney & Urinary Care", "Urology Consultation"],
    about: "On-call urology specialist support.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 11,
    name: "Dr. Rinku Gupta",
    nameHindi: "Dr. Rinku Gupta",
    specialization: "Pediatrician",
    specializationHindi: "Pediatrician",
    experience: "Evening OPD",
    education: "MBBS, MD",
    image: "/images/doctors/doctor-05.jpg",
    availability: "As Scheduled",
    timings: ["9 PM - 10 PM"],
    consultationFee: 500,
    feeLabel: "Rs.500",
    languages: ["Hindi", "English"],
    specialties: ["Child Health", "Pediatric Checkup", "Fever & Vaccination"],
    about: "Evening pediatric consultation for children.",
    isAvailable: true,
    onCall: false
  },
  {
    id: 12,
    name: "Dr. Vivek Sharma",
    nameHindi: "Dr. Vivek Sharma",
    specialization: "Pediatrician",
    specializationHindi: "Pediatrician",
    experience: "On Call",
    education: "MBBS, DCH",
    image: "/images/doctors/doctor-06.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: 500,
    feeLabel: "Rs.500",
    languages: ["Hindi", "English"],
    specialties: ["Child Consultation", "Pediatric Advice", "Emergency Pediatric Support"],
    about: "On-call pediatric support for families.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 13,
    name: "Dr. R. K. Shrivastav",
    nameHindi: "Dr. R. K. Shrivastav",
    specialization: "Pediatrician",
    specializationHindi: "Pediatrician",
    experience: "On Call",
    education: "MBBS, MD",
    image: "/images/doctors/doctor-01.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: 500,
    feeLabel: "Rs.500",
    languages: ["Hindi", "English"],
    specialties: ["Child Specialist", "Pediatric Follow-up", "Child Wellness"],
    about: "On-call pediatric specialist support.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 14,
    name: "Dr. Roma Rumaray",
    nameHindi: "Dr. Roma Rumaray",
    specialization: "Anesthetist",
    specializationHindi: "Anesthetist",
    experience: "On Call",
    education: "MBBS, MD",
    image: "/images/doctors/doctor-02.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: null,
    feeLabel: "Fee on call",
    languages: ["Hindi", "English"],
    specialties: ["Anaesthesia Support", "Surgical Backup", "Procedure Care"],
    about: "On-call anaesthesia specialist support.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 15,
    name: "Dr. Sanchit Singh",
    nameHindi: "Dr. Sanchit Singh",
    specialization: "Gastroenterologist",
    specializationHindi: "Gastroenterologist",
    experience: "On Call",
    education: "MBBS, MD, DNB (Gastro)",
    image: "/images/doctors/doctor-03.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: 1000,
    feeLabel: "Rs.1000",
    languages: ["Hindi", "English"],
    specialties: ["Gastro Consultation", "Liver & Stomach Care", "Digestive Disorders"],
    about: "On-call gastroenterology specialist consultation.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 16,
    name: "Dr. Sanjay Gupta",
    nameHindi: "Dr. Sanjay Gupta",
    specialization: "ENT Specialist",
    specializationHindi: "ENT Specialist",
    experience: "On Call",
    education: "MBBS, MS",
    image: "/images/doctors/doctor-04.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: 1000,
    feeLabel: "Rs.1000",
    languages: ["Hindi", "English"],
    specialties: ["ENT Consultation", "Sinus & Ear Care", "Throat Disorders"],
    about: "On-call ENT specialist support.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 17,
    name: "Dr. Pranav Tyagi",
    nameHindi: "Dr. Pranav Tyagi",
    specialization: "Nephrologist",
    specializationHindi: "Nephrologist",
    experience: "On Call",
    education: "MBBS, MD, DRMD",
    image: "/images/doctors/doctor-05.jpg",
    availability: "On Call",
    timings: ["Available on call"],
    consultationFee: 1000,
    feeLabel: "Rs.1000",
    languages: ["Hindi", "English"],
    specialties: ["Kidney Specialist", "Nephrology Consultation", "Renal Care"],
    about: "On-call nephrology specialist consultation.",
    isAvailable: true,
    onCall: true
  },
  {
    id: 18,
    name: "Dr. Ankit K. Jain",
    nameHindi: "Dr. Ankit K. Jain",
    specialization: "Radiologist",
    specializationHindi: "Radiologist",
    experience: "Day OPD",
    education: "MBBS, MD",
    image: "/images/doctors/doctor-06.jpg",
    availability: "As Scheduled",
    timings: ["10 AM - 2 PM"],
    consultationFee: null,
    feeLabel: "Fee on call",
    languages: ["Hindi", "English"],
    specialties: ["Radiology Review", "Imaging Consultation", "X-Ray & Scan Support"],
    about: "Radiology consultation during daytime OPD hours.",
    isAvailable: true,
    onCall: false
  },
  {
    id: 19,
    name: "Dr. Nikhil Saxena",
    nameHindi: "Dr. Nikhil Saxena",
    specialization: "Dental Surgeon",
    specializationHindi: "Dental Surgeon",
    experience: "Daily Evening",
    education: "BDS, MDS",
    image: "/images/doctors/doctor-01.jpg",
    availability: "Daily",
    timings: ["8 PM - 9 PM"],
    consultationFee: null,
    feeLabel: "Fee on call",
    languages: ["Hindi", "English"],
    specialties: ["Dental Consultation", "Tooth Care", "Oral Health"],
    about: "Daily evening dental consultation support.",
    isAvailable: true,
    onCall: false
  },
  {
    id: 20,
    name: "Dr. Chandan Kumar",
    nameHindi: "Dr. Chandan Kumar",
    specialization: "Senior Consultant Physiotherapist",
    specializationHindi: "Senior Consultant Physiotherapist",
    experience: "Mon-Sun",
    education: "BPT, MPT, MIAP",
    image: "/images/doctors/doctor-02.jpg",
    availability: "Mon-Sun",
    timings: ["Mon-Sat: 7 PM - 10 PM", "Sunday: 10 AM - 1 PM"],
    consultationFee: null,
    feeLabel: "Fee on call",
    languages: ["Hindi", "English"],
    specialties: ["Physiotherapy", "Pain Relief", "Rehabilitation"],
    about: "Senior consultant physiotherapist with weekday and Sunday slots.",
    isAvailable: true,
    onCall: false
  }
];

// 50 Testimonials from nearby areas
export const testimonials = [
  { id: 1, name: "Ramesh Kumra", nameHindi: "रमेश कुमार", location: "Old Kondli", locationHindi: "पुरानी कोंडली", review: "Excellent care! Dr. Sandeep Kumar is very experienced. Best hospital in the area.", reviewHindi: "बेहतरीन देखभाल! डॉ. संदीप कुमार बहुत अनुभवी हैं।", rating: 5, service: "General Medicine" },
  { id: 2, name: "Vijay Singh", nameHindi: "विजय सिंह", location: "Trilokpuri", locationHindi: "त्रिलोकपुरी", review: "Best hospital in East Delhi. Clean and well-maintained. Doctors are experienced.", reviewHindi: "पूर्वी दिल्ली का सबसे अच्छा अस्पताल।", rating: 5, service: "General Medicine" },
  { id: 3, name: "Sunita Sharma", nameHindi: "सुनीता शर्मा", location: "Kalyanpuri", locationHindi: "कल्याणपुरी", review: "Very good hospital with affordable fees. Staff is caring and professional.", reviewHindi: "किफायती फीस के साथ बहुत अच्छा अस्पताल।", rating: 5, service: "OPD Services" },
  { id: 4, name: "Amit Gupta", nameHindi: "अमित गुप्ता", location: "Khichripur", locationHindi: "खिचड़ीपुर", review: "Excellent orthopedic care! My knee pain was treated effectively. Highly satisfied!", reviewHindi: "उत्कृष्ट ऑर्थोपेडिक देखभाल! घुटने का दर्द ठीक हुआ।", rating: 5, service: "Orthopedics" },
  { id: 5, name: "Priya Verma", nameHindi: "प्रिया वर्मा", location: "Mayur Vihar", locationHindi: "मयूर विहार", review: "Great experience. Gynecology department is excellent. Dr. Sharma is very caring.", reviewHindi: "बहुत अच्छा अनुभव। स्त्री रोग विभाग उत्कृष्ट है।", rating: 5, service: "Gynecology" },
  { id: 6, name: "Rajesh Yadav", nameHindi: "राजेश यादव", location: "Gharoli", locationHindi: "घरोली", review: "Emergency service is very fast. They saved my father's life. Thank you!", reviewHindi: "इमरजेंसी सेवा बहुत तेज है। मेरे पिता की जान बचाई।", rating: 5, service: "Emergency Care" },
  { id: 7, name: "Neha Malhotra", nameHindi: "नेहा मल्होत्रा", location: "Dallupura", locationHindi: "दल्लूपुरा", review: "Very happy with the treatment. Staff is friendly and fees are reasonable.", reviewHindi: "इलाज से बहुत खुश। स्टाफ मिलनसार है।", rating: 5, service: "General Consultation" },
  { id: 8, name: "Kavita Devi", nameHindi: "कविता देवी", location: "Mandawali", locationHindi: "मंडावली", review: "Best place for delivery. Dr. Sneha is very caring. Safe delivery.", reviewHindi: "डिलीवरी के लिए सबसे अच्छी जगह।", rating: 5, service: "Maternity" },
  { id: 9, name: "Anita Rani", nameHindi: "अनीता रानी", location: "IP Extension", locationHindi: "आईपी एक्सटेंशन", review: "Came for child checkup. Pediatric department is very good. Clean environment.", reviewHindi: "बच्चे के चेकअप के लिए आई। पीडियाट्रिक विभाग बहुत अच्छा।", rating: 5, service: "Pediatrics" },
  { id: 10, name: "Meena Kumari", nameHindi: "मीना कुमारी", location: "New Kondli", locationHindi: "नई कोंडली", review: "Regular patient for 15 years. Best hospital in Kondli. Highly recommended!", reviewHindi: "5 साल से नियमित मरीज। बहुत अच्छा अस्पताल।", rating: 5, service: "General Medicine" },
  { id: 11, name: "Suresh Kumar", nameHindi: "सुरेश कुमार", location: "Patparganj", locationHindi: "पटपड़गंज", review: "Lab reports come on same day. Very convenient and accurate. Good prices.", reviewHindi: "लैब रिपोर्ट उसी दिन आती है। सुविधाजनक।", rating: 5, service: "Diagnostic Lab" },
  { id: 12, name: "Sunita Yadav", nameHindi: "सुनीता यादव", location: "New Kondli ", locationHindi: "न्यू कोंडली ", review: "Vitamin D test done. Report was accurate. Good diagnostic facility.", reviewHindi: "विटामिन डी टेस्ट हुआ। सटीक रिपोर्ट। अच्छी सुविधा।", rating: 5, service: "Vitamin Test" },
  { id: 13, name: "Urmila Devi", nameHindi: "उर्मिला देवी", location: "Dallupura Extension", locationHindi: "दल्लूपुरा एक्सटेंशन", review: "Very satisfied with overall service. Will recommend to everyone.", reviewHindi: "सेवा से बहुत संतुष्ट। सबको सिफारिश करूंगी।", rating: 5, service: "Overall Service" },
  { id: 14, name: "Ravi Sharma", nameHindi: "रवि शर्मा", location: "Vinod Nagar", locationHindi: "विनोद नगर", review: "Staff is very helpful. Doctors explain everything properly. Good experience.", reviewHindi: "स्टाफ बहुत मददगार है। डॉक्टर सब समझाते हैं।", rating: 5, service: "General Medicine" },
  { id: 15, name: "Deepak Verma", nameHindi: "दीपक वर्मा", location: "Hasanpur", locationHindi: "हसनपुर", review: "X-Ray done quickly. Digital reports. Very satisfied with service.", reviewHindi: "एक्स-रे जल्दी हो गया। डिजिटल रिपोर्ट। संतुष्ट।", rating: 5, service: "X-Ray" },
  { id: 16, name: "Pooja Gupta", nameHindi: "पूजा गुप्ता", location: "Gazipur", locationHindi: "गाजीपुर", review: "Ultrasound facility is very good. Quick reports. Professional staff.", reviewHindi: "अल्ट्रासाउंड सुविधा बहुत अच्छी। जल्दी रिपोर्ट।", rating: 5, service: "Ultrasound" },
  { id: 17, name: "Mohd. Salim", nameHindi: "मोहम्मद सलीम", location: "Kondli Village", locationHindi: "कोंडली गांव", review: "Very good hospital. Emergency services are excellent. 24/7 available.", reviewHindi: "बहुत अच्छा अस्पताल। इमरजेंसी सेवाएं उत्कृष्ट।", rating: 5, service: "Emergency" },
  { id: 18, name: "Geeta Rani", nameHindi: "गीता रानी", location: "Pandav Nagar", locationHindi: "पांडव नगर", review: "Sugar checkup done. Same day report. Very convenient location.", reviewHindi: "शुगर चेकअप हो गया। उसी दिन रिपोर्ट।", rating: 5, service: "Blood Test" },
  { id: 19, name: "Ashok Kumar", nameHindi: "अशोक कुमार", location: "Shakarpur", locationHindi: "शकरपुर", review: "Very experienced doctors. Treatment is effective. Recommended to all.", reviewHindi: "बहुत अनुभवी डॉक्टर। इलाज प्रभावी।", rating: 5, service: "General Medicine" },
  { id: 20, name: "Vikram Singh", nameHindi: "विक्रम सिंह", location: "Akshardham", locationHindi: "अक्षरधाम", review: "ICU facility saved my mother. Excellent critical care. Very grateful.", reviewHindi: "आईसीयू सुविधा ने मेरी माँ को बचाया। आभारी।", rating: 5, service: "ICU" },
  { id: 21, name: "Mamta Sharma", nameHindi: "ममता शर्मा", location: "Laxmi Nagar", locationHindi: "लक्ष्मी नगर", review: "Pregnancy care was excellent. Regular checkups done properly. Safe delivery.", reviewHindi: "प्रेगनेंसी केयर उत्कृष्ट थी। सेफ डिलीवरी।", rating: 5, service: "Maternity" },
  { id: 22, name: "Rakesh Pal", nameHindi: "राकेश पाल", location: "East Vinod Nagar", locationHindi: "पूर्वी विनोद नगर", review: "Best hospital for surgery. Modern operation theater. Quick recovery.", reviewHindi: "सर्जरी के लिए सबसे अच्छा। जल्दी रिकवरी।", rating: 5, service: "Surgery" },
  { id: 23, name: "Sarita Devi", nameHindi: "सरिता देवी", location: "Chilla Village", locationHindi: "चिल्ला गांव", review: "Affordable treatment. Good doctors. Hospital is clean and hygienic.", reviewHindi: "किफायती इलाज। अच्छे डॉक्टर। साफ-सुथरा।", rating: 5, service: "General Medicine" },
  { id: 24, name: "Sangeeta Devi", nameHindi: "संगीता देवी", location: "Trilokpuri Block 27", locationHindi: "त्रिलोकपुरी ब्लॉक 27", review: "ECG done in 10 minutes. Report came immediately. Very fast service.", reviewHindi: "10 मिनट में ईसीजी। तुरंत रिपोर्ट। तेज सेवा।", rating: 5, service: "ECG" },
  { id: 25, name: "Naresh Kumar", nameHindi: "नरेश कुमार", location: "Mandoli", locationHindi: "मंडोली", review: "Came for fracture treatment. Excellent orthopedic care. Fast healing.", reviewHindi: "फ्रैक्चर के इलाज के लिए आया। उत्कृष्ट देखभाल।", rating: 5, service: "Orthopedics" },
  { id: 26, name: "Rekha Gupta", nameHindi: "रेखा गुप्ता", location: "Kalyanpuri Block 12", locationHindi: "कल्याणपुरी ब्लॉक 12", review: "Child vaccination done on time. Doctor explained everything. Good care.", reviewHindi: "समय पर टीकाकरण। डॉक्टर ने सब समझाया।", rating: 5, service: "Vaccination" },
  { id: 27, name: "Prem Chand", nameHindi: "प्रेम चंद", location: "New Ashok Nagar", locationHindi: "न्यू अशोक नगर", review: "Thyroid test facility is good. Accurate results. Reasonable price.", reviewHindi: "थायरॉयड टेस्ट सुविधा अच्छी। सटीक परिणाम।", rating: 5, service: "Thyroid Test" },
  { id: 28, name: "Suman Lata", nameHindi: "सुमन लता", location: "Khichripur Village", locationHindi: "खिचड़ीपुर गांव", review: "Women's health checkup done. Very comfortable environment. Good staff.", reviewHindi: "महिला स्वास्थ्य जांच हुई। आरामदायक माहौल।", rating: 5, service: "Women's Health" },
  { id: 29, name: "Bharat Singh", nameHindi: "भरत सिंह", location: "Gharoli Extension", locationHindi: "घरोली एक्सटेंशन", review: "Blood pressure treatment going well. Regular followups. Good doctor.", reviewHindi: "बीपी का इलाज ठीक चल रहा। नियमित फॉलोअप।", rating: 5, service: "BP Treatment" },
  { id: 30, name: "Kusum Devi", nameHindi: "कुसुम देवी", location: "Dallupura Village", locationHindi: "दल्लूपुरा गांव", review: "Senior citizen friendly. Wheelchair available. Very helpful staff.", reviewHindi: "बुजुर्गों के लिए अनुकूल। व्हीलचेयर उपलब्ध।", rating: 5, service: "Senior Care" },
  { id: 31, name: "Rahul Dedha", nameHindi: "राहुल वर्मा", location: "Mayur Vihar Phase 1", locationHindi: "मयूर विहार फेज 1", review: "Complete health checkup done. All tests in one place. Convenient.", reviewHindi: "पूर्ण स्वास्थ्य जांच हुई। सब टेस्ट एक जगह।", rating: 5, service: "Health Checkup" },
  { id: 32, name: "Shanti Devi", nameHindi: "शांति देवी", location: "Patparganj Industrial Area", locationHindi: "पटपड़गंज", review: "Diabetes management is good. Regular monitoring. Good results.", reviewHindi: "डायबिटीज प्रबंधन अच्छा। नियमित निगरानी।", rating: 5, service: "Diabetes Care" },
  { id: 33, name: "Dinesh Kumar", nameHindi: "दिनेश कुमार", location: "Kondli Depot", locationHindi: "कोंडली डिपो", review: "Ambulance came within 15 minutes. Life saving service. Thank you.", reviewHindi: "15 मिनट में एम्बुलेंस आई। जान बचाने वाली सेवा।", rating: 5, service: "Ambulance" },
  { id: 34, name: "Sunil Bhati", nameHindi: "सुनील शर्मा", location: "Mandawali Fazalpur", locationHindi: "मंडावली फजलपुर", review: "Liver function test done. Same day report. Very professional.", reviewHindi: "लिवर टेस्ट हुआ। उसी दिन रिपोर्ट। प्रोफेशनल।", rating: 5, service: "LFT Test" },
  { id: 35, name: "Harish Chandra", nameHindi: "हरीश चंद्र", location: "Hasanpur Village", locationHindi: "हसनपुर गांव", review: "Joint pain treatment is excellent. Physiotherapy helped a lot.", reviewHindi: "जोड़ों के दर्द का इलाज उत्कृष्ट। फिजियोथेरेपी से फायदा।", rating: 5, service: "Physiotherapy" },
  { id: 36, name: "Kamla Devi", nameHindi: "कमला देवी", location: "Gazipur Dairy Farm", locationHindi: "गाजीपुर डेयरी फार्म", review: "Kidney function test done. Report accuracy is good. Trusted lab.", reviewHindi: "किडनी टेस्ट हुआ। रिपोर्ट सटीक। विश्वसनीय लैब।", rating: 5, service: "KFT Test" },
  { id: 37, name: "Pushpa Devi", nameHindi: "पुष्पा देवी", location: "Kalyanpuri Block 8", locationHindi: "कल्याणपुरी ब्लॉक 8", review: "Urine test facility is good. Quick reports. Clean sample collection.", reviewHindi: "यूरिन टेस्ट सुविधा अच्छी। जल्दी रिपोर्ट।", rating: 5, service: "Urine Test" },
  { id: 38, name: "Asha Rani", nameHindi: "आशा रानी", location: "Trilokpuri Block 20", locationHindi: "त्रिलोकपुरी ब्लॉक 20", review: "Child fever treatment was effective. Doctor was very patient.", reviewHindi: "बच्चे का बुखार ठीक हुआ। डॉक्टर धैर्यवान थे।", rating: 5, service: "Pediatrics" },
  { id: 39, name: "Mohan Lal", nameHindi: "मोहन लाल", location: "Vinod Nagar East", locationHindi: "विनोद नगर पूर्व", review: "Cholesterol test done. Diet advice given. Very helpful doctor.", reviewHindi: "कोलेस्ट्रॉल टेस्ट हुआ। डाइट सलाह मिली।", rating: 5, service: "Lipid Profile" },
  { id: 40, name: "Saroj Bala", nameHindi: "सरोज बाला", location: "IP Extension Block A", locationHindi: "आईपी एक्सटेंशन", review: "Pelvic ultrasound done. Female technician available. Comfortable.", reviewHindi: "पेल्विक अल्ट्रासाउंड हुआ। महिला तकनीशियन। आरामदायक।", rating: 5, service: "Pelvic Scan" },
  { id: 41, name: "Vijay Kumar", nameHindi: "विजय कुमार", location: "Gazipur Border", locationHindi: "गाजीपुर बॉर्डर", review: "Accident emergency handled very well. Quick treatment. Life saved.", reviewHindi: "दुर्घटना इमरजेंसी अच्छी तरह संभाली। जान बची।", rating: 5, service: "Emergency" },
  { id: 42, name: "Ram Kishan", nameHindi: "राम किशन", location: "Chilla Sports Complex", locationHindi: "चिल्ला स्पोर्ट्स कॉम्प्लेक्स", review: "Sports injury treated well. Quick recovery. Excellent physiotherapy.", reviewHindi: "खेल चोट का इलाज अच्छा। जल्दी रिकवरी।", rating: 5, service: "Sports Injury" },
  { id: 43, name: "Manju Sharma", nameHindi: "मंजू शर्मा", location: "Pandav Nagar Industrial Area", locationHindi: "पांडव नगर", review: "Pregnancy ultrasound was detailed. Baby health explained properly.", reviewHindi: "प्रेगनेंसी अल्ट्रासाउंड विस्तृत था। बच्चे की सेहत समझाई।", rating: 5, service: "Pregnancy Scan" },
  { id: 44, name: "Anil Kumar", nameHindi: "अनिल कुमार", location: "Shakarpur Khas", locationHindi: "शकरपुर खास", review: "Minor surgery done. No complications. Recovery was smooth.", reviewHindi: "मामूली सर्जरी हुई। कोई जटिलता नहीं। अच्छी रिकवरी।", rating: 5, service: "Minor Surgery" },
  { id: 45, name: "Kiran Devi", nameHindi: "किरण देवी", location: "Laxmi Nagar Metro", locationHindi: "लक्ष्मी नगर मेट्रो", review: "Regular health checkup done. All parameters checked. Affordable.", reviewHindi: "नियमित स्वास्थ्य जांच हुई। सब पैरामीटर चेक। किफायती।", rating: 5, service: "Full Checkup" },
  { id: 46, name: "Tej Pal", nameHindi: "तेज पाल", location: "East Vinod Nagar Metro", locationHindi: "पूर्वी विनोद नगर मेट्रो", review: "Asthma treatment is effective. Breathing exercises taught. Helpful.", reviewHindi: "अस्थमा इलाज प्रभावी। सांस व्यायाम सिखाए। मददगार।", rating: 5, service: "Respiratory" },
  { id: 47, name: "Radha Devi", nameHindi: "राधा देवी", location: "Trilokpuri Block 32", locationHindi: "त्रिलोकपुरी ब्लॉक 32", review: "Allergy testing done. Root cause found. Treatment working well.", reviewHindi: "एलर्जी टेस्टिंग हुई। मूल कारण मिला। इलाज काम कर रहा।", rating: 5, service: "Allergy Test" },
  { id: 48, name: "Satish Kumar", nameHindi: "सतीश कुमार", location: "Mandoli Industrial Area", locationHindi: "मंडोली", review: "Work injury treated. Insurance claim documents provided. Helpful.", reviewHindi: "काम की चोट का इलाज। बीमा दस्तावेज दिए। मददगार।", rating: 5, service: "Injury Treatment" },
  { id: 49, name: "Seema Rani", nameHindi: "सीमा रानी", location: "Kalyanpuri Block 17", locationHindi: "कल्याणपुरी ब्लॉक 17", review: "PCOD treatment going well. Regular monitoring. Good gynecologist.", reviewHindi: "पीसीओडी इलाज ठीक चल रहा। नियमित निगरानी। अच्छी डॉक्टर।", rating: 5, service: "PCOD Treatment" },
  { id: 50, name: "Lalchand", nameHindi: "लालचंद", location: "Gharoli Dairy Farm", locationHindi: "घरोली डेयरी फार्म", review: "Affordable medicine prices. Pharmacy inside hospital. Convenient.", reviewHindi: "किफायती दवाई। फार्मेसी अस्पताल के अंदर। सुविधाजनक।", rating: 5, service: "Pharmacy" },
];

export const facilities = [
  { title: "ISO Certified", titleHindi: "आईएसओ प्रमाणित", description: "Quality assured healthcare", icon: "Award" },
  { title: "Multi-specialty", titleHindi: "मल्टी-स्पेशियलिटी", description: "All departments under one roof", icon: "Building" },
  { title: "24/7 Emergency", titleHindi: "24/7 इमरजेंसी", description: "Round-the-clock care", icon: "Clock" },
  { title: "Digital X-Ray", titleHindi: "डिजिटल एक्स-रे", description: "Advanced imaging", icon: "Scan" },
  { title: "Ultrasound", titleHindi: "अल्ट्रासाउंड", description: "Complete sonography", icon: "Monitor" },
  { title: "Modern Lab", titleHindi: "आधुनिक लैब", description: "Same-day reports", icon: "TestTube" },
  { title: "Affordable Care", titleHindi: "किफायती इलाज", description: "Quality at low cost", icon: "Heart" },
  { title: "Ambulance Service", titleHindi: "एम्बुलेंस सेवा", description: "24/7 ambulance", icon: "HeartPulse" }
];

export const footerServices = [
  "OPD Services", "Emergency Care", "X-Ray", "Ultrasound", "Blood Tests",
  "Surgery", "Orthopedics", "Gynecology", "Pediatrics", "ECG",
  "Health Checkup", "Physiotherapy", "Diagnostic Lab", "Vaccination"
];

export const faqList = [
  { q: "How can I contact the hospital?", qHindi: "हॉस्पिटल से संपर्क कैसे करें?", a: "Call +91-8700628028 or WhatsApp us for any enquiry.", aHindi: "किसी भी जानकारी के लिए +91-8700628028 पर कॉल या व्हाट्सएप करें।" },
  { q: "Emergency service timing?", qHindi: "इमरजेंसी सेवा का समय?", a: "24/7 available. Come anytime.", aHindi: "24/7 उपलब्ध। कभी भी आएं।" },
  { q: "Where is the hospital?", qHindi: "हॉस्पिटल कहां है?", a: "Plot D-3, Main Market, Old Kondli, Delhi 110096", aHindi: "प्लॉट D-3, मेन मार्केट, पुरानी कोंडली, दिल्ली 110096" },
  { q: "What services are available?", qHindi: "क्या सेवाएं उपलब्ध हैं?", a: "OPD, Emergency, Lab, X-Ray, Ultrasound, Surgery, and more.", aHindi: "ओपीडी, इमरजेंसी, लैब, एक्स-रे, अल्ट्रासाउंड, सर्जरी आदि।" },
  { q: "What are the consultation fees?", qHindi: "परामर्श शुल्क क्या है?", a: "Starting from Rs.200. Varies by specialist.", aHindi: "200 रुपये से शुरू। विशेषज्ञ के अनुसार अलग।" },
  { q: "Is parking available?", qHindi: "पार्किंग उपलब्ध है?", a: "Yes, free parking available.", aHindi: "हां, मुफ्त पार्किंग उपलब्ध।" },
  { q: "Where is Relax Diagnostics?", qHindi: "रिलैक्स डायग्नोस्टिक्स कहां है?", a: "D-1, Main Market, Near SBI, Kondli Extension. Call 9990187799.", aHindi: "D-1, मेन मार्केट, SBI के पास, कोंडली एक्सटेंशन। कॉल 9990187799।" },
  { q: "Do you have ambulance service?", qHindi: "एम्बुलेंस सेवा है?", a: "Yes, 24/7 ambulance service available. Call 8700628028.", aHindi: "हां, 24/7 एम्बुलेंस सेवा उपलब्ध। कॉल 8700628028।" },
  { q: "What blood tests are available?", qHindi: "कौन से ब्लड टेस्ट होते हैं?", a: "CBC, Sugar, Thyroid, Lipid Profile, KFT, LFT and more.", aHindi: "सीबीसी, शुगर, थायरॉयड, लिपिड प्रोफाइल, केएफटी, एलएफटी आदि।" },
  { q: "Is OPD available on Sunday?", qHindi: "रविवार को ओपीडी है?", a: "Yes, OPD available all 7 days from 9AM to 9PM.", aHindi: "हां, सातों दिन सुबह 9 से रात 9 तक ओपीडी।" }
];

export const translations = {
  en: {
    home: "Home", services: "Services", doctors: "Doctors", about: "About", contact: "Contact",
    emergencyCall: "Emergency Call", callNow: "Call Now",
    whatsapp: "WhatsApp", sendMessage: "Send Message", ourServices: "Our Services",
    ourDoctors: "Our Doctors", aboutUs: "About Us", contactUs: "Contact Us", quickLinks: "Quick Links",
    getDirections: "Get Directions", viewAll: "View All", readMore: "Read More",
    yearsExperience: "Years Experience", happyPatients: "Happy Patients", emergencyCare: "Emergency Care",
    pageNotFound: "Page Not Found", goHome: "Go to Home", knowMore: "Know More", testBooking: "Book Test",
    diagnostics: "Diagnostics"
  },
  hi: {
    home: "होम", services: "सेवाएं", doctors: "डॉक्टर", about: "हमारे बारे में", contact: "संपर्क",
    emergencyCall: "इमरजेंसी कॉल", callNow: "अभी कॉल करें",
    whatsapp: "व्हाट्सएप", sendMessage: "मैसेज भेजें", ourServices: "हमारी सेवाएं",
    ourDoctors: "हमारे डॉक्टर", aboutUs: "हमारे बारे में", contactUs: "संपर्क करें", quickLinks: "त्वरित लिंक",
    getDirections: "दिशा-निर्देश", viewAll: "सभी देखें", readMore: "और पढ़ें",
    yearsExperience: "वर्षों का अनुभव", happyPatients: "खुश मरीज", emergencyCare: "इमरजेंसी सेवा",
    pageNotFound: "पेज नहीं मिला", goHome: "होम पर जाएं", knowMore: "और जानें", testBooking: "टेस्ट बुक करें",
    diagnostics: "डायग्नोस्टिक्स"
  }
};
